version: "3.8"

services:
  dcm-to-png:
    container_name: dcm-to-png
    image: dcm-to-png
    build:
      context: ./dcm-to-png
  devbox-db:
    image: "healthsamurai/aidboxdb:13.2"
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:       devbox
  devbox:
    image: "healthsamurai/devbox:edge"
    depends_on:
      - devbox-db
    links:
      - "devbox-db:database"
    ports:
      - "8080:8080"
    env_file:
     - .env.aidbox
    volumes:
    - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh:cached
    - ./zrc:/zrc
    - ./config:/var/config:cached
  devbox-healthcheck:
     image: curlimages/curl
     entrypoint: /bin/sleep 10000
     links:
     - devbox
     depends_on:
     - devbox
     healthcheck:
       test: curl --fail http://devbox:8080/__healthcheck || exit 1
       interval: 1s
       timeout: 20s
       retries: 100

  app:
    build: ./backend-nodejs
    volumes:
    - ./backend-nodejs/src:/usr/src/app/src
    env_file:
    - .env.app
    depends_on:
      devbox-healthcheck:
        condition: service_healthy
    links:
    - devbox

  sdc:
    image: bedasoftware/aidbox-sdc:latest
    depends_on:
      devbox-healthcheck:
        condition: service_healthy
    links:
    - devbox
    env_file:
    - .env.sdc
    tty: true
