apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: hadleylaboratory
  region: us-east-2
  version: "1.22"
managedNodeGroups:
  - name: ng-1
    instanceType: t3a.medium
    desiredCapacity: 2
  - name: ng-2
    instanceType: t3a.large
    desiredCapacity: 2
