apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployer
  namespace: staging
rules:
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  resourceNames:
  - backend
  - frontend
  verbs: ["get", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ci-cd-deploy
  namespace: staging
subjects:
- kind: User
  name: github-actions-ucfwealth
  namespace: staging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployer
