---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: NodePort
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    workload: backend
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    workload: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: dcm-to-png
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    workload: dcm-to-png
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      workload: backend
  template:
    metadata:
      labels:
        workload: backend
    spec:
      containers:
      - name: backend
        image: bedasoftware/ucfwealth-aidbox-app:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "4Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
        ports:
        - containerPort: 3000
        envFrom:
          - configMapRef:
              name: app
          - secretRef:
              name: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      workload: frontend
  template:
    metadata:
      labels:
        workload: frontend
    spec:
      containers:
      - name: frontend
        image: bedasoftware/ucfwealth-frontend:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512M"
            cpu: "500m"
          limits:
            memory: "512M"
        ports:
        - containerPort: 5000
        envFrom:
          - configMapRef:
              name: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dcm-to-png
spec:
  replicas: 1
  selector:
    matchLabels:
      workload: dcm-to-png
  template:
    metadata:
      labels:
        workload: dcm-to-png
    spec:
      containers:
      - name: dcm-to-png
        image: bedasoftware/dcm-to-png:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "1Gi"
        ports:
        - containerPort: 5000
