apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configuration.yaml

configMapGenerator:
  - name: postgres
    literals:
      - PGDATA=/data/pg
      - POSTGRES_DB=postgres

  - name: postgres-conf
    files: ["./postgresql.conf"]
